### ISSUE TITLE
CustomAttributes and or CustomStyles

### ISSUE THREAD

**Issue by Mashiane** [asigloo/vue-dynamic-forms#145]
**Is your feature request related to a problem? Please describe.**
No this is not currently a problem but just a suggestion. Some frameworks come with pre-defined attributes that you need to define for the look and feel.  

**Describe the solution you'd like**
Whist there is a customClass property for fields, perhaps customAttributes and or customStyles that could receive a key value pairs would also suffice. These of course would pick up the css from whatever cascading style sheet file added on the vue project. As an example, the tags for vuetify start with v- and whilst I understand that this is generic, how does one make it work with a particular framework, lets say BootstrapVue for example which depend on additional attributes.

**Describe alternatives you've considered**

**Additional context**

**Comment by alvarosaburido** [comment]
Hello @Mashiane thanks for writing! I really like the idea of adding `customStyles` and `customAttributes` along with `customClasses` in the fields, I have to check some errors I had in `Vue 3` when binding attributes dynamically,  but the first is sure going.

Are you using the  `2.x` version for Vue2 or the `3.x.x` version for Vue3 in the  `next` channel?

**Comment by Mashiane** [comment]
Vue2 as vuetify is still on that iteration. Thanks.

**Comment by alvarosaburido** [comment]
@Mashiane merged on 2.x branch, thanks for the suggestion
