### ISSUE TITLE
Dual version installation support (Vue2, Vue3)

### ISSUE THREAD

**Issue by alvarosaburido** [asigloo/vue-dynamic-forms#199]
**Is your feature request related to a problem? Please describe.**
At. the moment, Vue2 version lives on master 2.x and Vue3 support on next

**Describe the solution you'd like**
I want to use the code on `next` for both Vue2 and Vue3

**Describe alternatives you've considered**
https://github.com/vuejs/vuefire/blob/v3/src/vuefire/firestore.ts#L164

**Additional context**

**Comment by userquin** [comment]
@alvarosaburido why not using `vue-demi` with the same codebase? See for example `@vueuse`, you can switch between `vue2` and `vue3` (maybe we can have some troubles since `vue2` is not 100% compatible with `composition-api`).

**Comment by alvarosaburido** [comment]
@userquin I tried once to use it, but talking with the vue core team, `vue-demi` works well for libraries that doesnt render any components.

The rendering from vue2 to vue3 is completly different and have too many breaking changes.

If you check, example `@vueuse`, is all typescript composable functions, thats why works well with vue-demi.

**Comment by userquin** [comment]
@alvarosaburido and what about using template on SFC instead render fucntion? Since you have only a few components it shoudn't be a problem, they are no complex and so the render is resolved on build time.

Or, I'm missing something (is there a factory to use custom SFC provided by the user?)...

**Comment by alvarosaburido** [comment]
I had the same issues with SFC, at least the console errors where the same. Im almost sure SFC and render functions both  uses the same code for rendering.

I could be totally wrong, feel free to try it out. Maybe you have more luck than I did.
