### ISSUE TITLE
Is there any way to show hide fields ?

### ISSUE THREAD

**Issue by dinesh-88** [asigloo/vue-dynamic-forms#223]
Thanks for developing this library . Could you please help me on below questions ?

1. How can I show hide fields based on some conditions ?
2. How can I set values based on API response ?

Thanks

**Comment by alvarosaburido** [comment]
Hi @dinesh-88 I guess you refer to the current version so I will answer based on that assumption.

1. You can do it through CSS by adding a class using `customClass` or `customStyles` properties when defining the field like this: 

```
setup() {
  const isFieldVisible = ref(true);

  const form = computed( ()= >{
    id: 'test-form',
    fields: {
        name: TextField({
              label: 'Username',
                   customClass: isFieldVisible.value ? 'show': 'hide' 
              }),
    }
  })

  return {
    form
  }
}
```

**Comment by dinesh-88** [comment]
Hi @alvarosaburido

Thank for the reply. can you give me an example to set values  from API response ?

Thanks again

**Comment by alvarosaburido** [comment]
Hi sure, @dinesh-88, let's say you want to fill the options of a `SelectField` from and API call: 

```
setup() {
  const isFieldVisible = ref(true);
  let consoleOptions = ref([]);
  
  const form = computed( ()= >{
    id: 'test-form',
    fields: {
        console: SelectField({
              label: 'Console (Async Options)',
              options: consoleOptions.value,' 
        }),
    }
  })

  return {
    form
  }
}
```

**Comment by dinesh-88** [comment]
Thanks a lot
