### ISSUE TITLE
vue3 example codesandbox

### ISSUE THREAD

**Issue by miklosban** [asigloo/vue-dynamic-forms#235]
I've tried to create a vue3 app but failed  due to several problems first (webpack version, sass-loader version, node version). Finally I could solve all external error issues, but the app not worked me (I got only one warn message in browser debug: Failed to resolve component: dynamic-form...). I'm sure it was my fault because I don't know enough vue3 but a complete working codesandbox example (such like https://codesandbox.io/s/vue-dynamic-forms-ftzes for vue2 version) would help a lot.

Could you create a codesandbox example for vue3 version?

**Comment by OmgImAlexis** [comment]
@miklosban I'd suggest trying with vite and vue3. That's what I'm personally using and I found it quite easy to get up and running compared to the vue-cli project I first tried with.

**Comment by alvarosaburido** [comment]
I updated the Sandbox with the latest version @miklosban  https://codesandbox.io/s/vue-dynamic-forms-3xx-wfpix?file=/src/App.vue
