### ISSUE TITLE
Conditional logic

### ISSUE THREAD

**Issue by ChrisRAra** [asigloo/vue-dynamic-forms#238]
It would be great to have conditions for v-show / v-if to hide and show based on previous fields

**Comment by alvarosaburido** [comment]
You can actually achieve it with the `customClass` or `customStyle`  property and `display:none` the field depending on the condition

**Comment by ChrisRAra** [comment]
Awesome can you possibly show me an example of how?

**Comment by alvarosaburido** [comment]
Hey, @ChrisRAra you can take a look at the demos directory vue-3 example, there is a `General` demo where you can find examples of `customClass`.
