### ISSUE TITLE
tailwind css supports 

### ISSUE THREAD

**Issue by zeyadsharo** [asigloo/vue-dynamic-forms#241]

**Comment by OmgImAlexis** [comment]
@zeyadsharo care you add some more info?

**Comment by zeyadsharo** [comment]
I mean does support tailwind css  in dynamic form

**Comment by OmgImAlexis** [comment]
It already does.

**Comment by alvarosaburido** [comment]
Hi @zeyadsharo, I would like to kindly ask for the future to try to add a proper description when you open an issue on a repository, the more info the better.

Not sure which kind of tailwindcss support you need, you can use `customClass` on the fields factories to add tailwind utility classes like this 

```
 username: TextField({
    label: 'Username',
    customClass: 'text-xs border border-gray-400 bg-gray-200'
  }),
```
Worst case scenario, add a class to the input and use tailwind `@apply` to add the utilities on css in case you need to modify a nested element

I plan to add a Tailwindcss based example and a Tailwindcss theme in the near future here #262

**Comment by zeyadsharo** [comment]
@alvarosaburido 
the custom class works for parent not for input
` const form = computed(() => ({
      id: 'text-fields-demo',
      fields: {
        qty: NumberField({
          label: 'Quantity',
          customClass:'rounded bg-green-500'
        }),
      },
    }));`
![image](https://user-images.githubusercontent.com/33178745/125511370-fe765d1c-7984-4fda-b62c-d249feeae653.png)

**Comment by alvarosaburido** [comment]
In that case you can add a class and use tailwindcss `@apply`.
