### ISSUE TITLE
Feature: Ability to reset form

### ISSUE THREAD

**Issue by OmgImAlexis** [asigloo/vue-dynamic-forms#243]
**Is your feature request related to a problem? Please describe.**
A method that resets the form to the initial state. 

**Describe the solution you'd like**
Export `resetForm`.

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/asigloo/vue-dynamic-forms/pull/231 for those using `resetAfterSubmit` it'd be nice if we could then reset the form ourselves.

**Comment by alvarosaburido** [comment]
Hey there @OmgImAlexis I open a PR to enable this feature #283 

Will be possible to manually reset the form by using template refs

```html
<DynamicForm ref="formRef" :form="form" />
```

## Options API

You can access the dom element ref above by using template refs `this.$ref`

```typescript

methods: {
    resetForm() {
        this.$refs.formRef.resetForm
    }
}

```

## Composition API

You can access the dom element ref above by using template refs `const formRef = ref(null)`.

::: warning
Remember to add the ref to the return statement on the `setup` function so it's available on the template.
:::

```typescript

setup() {
    const formRef = ref(null);

    function resetForm() {
      formRef.value.resetForm()
    }

    return {
        formRef
    }
}

```
