### ISSUE TITLE
What's the recommended way to handle HTTP errors on form submission?

### ISSUE THREAD

**Issue by OmgImAlexis** [asigloo/vue-dynamic-forms#245]
Is there a best practise when using this library?

I'm trying to get a 401 to show a warning to the user that their user/pass is wrong.

**Comment by alvarosaburido** [comment]
@OmgImAlexis  the library is independent of how you want to send the data through HTTP.

You can use `@submit="handleSubmit"` 

```
function handleSubmit(values) {
   try {
      const res = await axios.post('<yourEndpointUrl>', values );
   } catch(error) {
       // Check if error is 401
   }
}

```
