### ISSUE TITLE
API for select field 

### ISSUE THREAD

**Issue by zeyadsharo** [asigloo/vue-dynamic-forms#268]

**Comment by alvarosaburido** [comment]
Please use the template to open an issue with meaningful description, otherwise, I will close it

**Comment by zeyadsharo** [comment]
ok,  I have this case 
to handle the select value change 
 change value of subcategory based on category 
**handleChange of Category**
doesn't SelectField support this case
```js
category: SelectField({
          label: 'Category',
          customClass: 'w-1/2 pr-4',
          options: store.getters.getCategory,
        }),

subCategory: SelectField({
          label: 'Category',
          customClass: 'w-1/2 pr-4',
          options: store.getters.subCategory,
        }),

```

**Comment by alvarosaburido** [comment]
Hi @zeyadsharo to listen to value change you need to do it at form level (not input level check [here](https://vue-dynamic-forms.alvarosaburido.dev/guide/usage.html#values-changed)

**Comment by alvarosaburido** [comment]
@zeyadsharo feel free to open it again if you have any other question regarding it
