### ISSUE TITLE
Bug when used as a nuxt module

### ISSUE THREAD

**Issue by nickap** [asigloo/vue-dynamic-forms#287]
### Version

3.x.x (Vue 3.x)

### Describe the bug

 FATAL  Package subpath './nuxt' is not defined by "exports" in /home/grapevine/Documents/vue_dynamic_forms/node_modules/@asigloo/vue-dynamic-forms/package.json 

✖ Nuxt Fatal Error 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './nuxt' is not defined by "exports" in 
/home/grapevine/Documents/vue_dynamic_forms/node_modules/@asigloo/vue-dynamic-forms/package.json

### Describe the bug

I wanted to use vue-dynamic-forms with nuxt following this guide:
https://alvarosaburido.dev/blog/deep-dive-into-vue-dynamic-forms

1. run: yarn create nuxt-app app_name
2. run: yarn add @asigloo/vue-dynamic-forms
3. use vue-dynamic-forms as a module
added in nuxt.config:
```
export default {
...
modules: ["@asigloo/vue-dynamic-forms/nuxt"],
...
};
```
4. run: yarn dev

This happens with both nuxt2 & nuxt3

### Expected behavior

I was expecting to be able to use this package as a nuxt module according to this PR https://github.com/asigloo/vue-dynamic-forms/pull/42

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 3.98 GB / 15.34 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.18.2 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    @asigloo/vue-dynamic-forms: ^3.18.0 => 3.18.0
```

### Validations

- [X] Read the [docs](https://vue-dynamic-forms-docs.netlify.app/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by nickap** [comment]
Seems I have to use [v2.0.1](https://github.com/asigloo/vue-dynamic-forms/releases/tag/v2.0.1) to work with nuxt (vue2)

**Comment by alvarosabu** [comment]
Hi there, currently there is no nuxt module for the version3, so yes for the v2 you will need to use the [v2.0.1](https://github.com/asigloo/vue-dynamic-forms/releases/tag/v2.0.1) 


@nickap  Will be between your use case to use it with nuxt3?
